
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: car-collection-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: car-collection-app-service
            port:
              number: 80
