
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: car-collection-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: car-collection.example.com  # Replace with your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: car-collection-app-service
            port:
              number: 80
  # Uncomment to add TLS when you have certificates
  # tls:
  # - hosts:
  #   - car-collection.example.com
  #   secretName: car-collection-tls
